name: "Run NPM Test"

on:
  workflow_dispatch:

jobs:
  test-ci:
    name: Run CI Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: |
          npm install --ignore-scripts true
          npm run test:ci
      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: Mocha Unit Tests
          path: test/results-report.json
          reporter: mocha-json
